version: "3.9"
services:
  web:
    build: .
    container_name: mosqueos_app
    environment:
      APP_ENV: development
    volumes:
      - ".:/app"
    ports:
      - "${APP_PORT:-3000}:3000"
      - "${DB_STUDIO_PORT:-5555}:5555"
    command: npm run dev
    networks:
      - mosqueos_net
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mosqueos_admin
    volumes:
      - mongodb:/data/db
    networks:
      - mosqueos_net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mosqueos_net
  mailhog:
    image: "mailhog/mailhog:latest"
    container_name: mosqueos_mail
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - mosqueos_net
networks:
  mosqueos_net:
    driver: bridge
volumes:
  mongodb:
